### ISSUE TITLE
Some valid rules are marked as invalid

### ISSUE THREAD

**Issue by AdamWr** [ameshkov/VscodeAdblockSyntax#1]
For example:
```
usatoday.com,tyda.se,nyheter24.se,nj.com,nationalreview.com,mlive.com,kwiss.me,html.net,fragbite.se,extremetech.com,demorgen.be,deadline.com,dayviews.com,wwd.com,wikia.com,mymotherlode.com,goldderby.com,spielaffe.de,winload.de,kino.de,golem.de#%#(function(b,d,e){function a(){}b={get:function(){return a},set:a},d={};Object.defineProperties(d,{spid_control_callback:b,content_control_callback:b,vid_control_callback:b});e=new Proxy({},{get:function(a,c){switch(c){case "config":return d;case "_setSpKey":throw Error();default:return a[c]}},set:function(a,c,b){switch(c){case "config":return!0;case "bootstrap":case "mms":return a[c]=b,!0;default:throw Error();}}});Object.defineProperty(window,"_sp_",{get:function(){return e},set:a})})();
southwalesargus.co.uk,swindonadvertiser.co.uk,theargus.co.uk,theboltonnews.co.uk,thetelegraphandargus.co.uk,eveningtimes.co.uk,dailyecho.co.uk,oxfordmail.co.uk,southwalesargus.co.uk,huffingtonpost.co.uk,radiotimes.com,huffingtonpost.com,gamesradar.com,giga.de,gamona.de,erdbeerlounge.de,chip.de#%#(function(o){function a(a){return{get:function(){return a},set:b}}function b(){}function c(){throw"Adguard: stopped a script execution.";}var d={},e=a(function(a){a(!1)}),f={},g=EventTarget.prototype.addEventListener;o(d,{spid_control_callback:a(b),content_control_callback:a(b),vid_control_callback:a(b)});o(f,{config:a(d),_setSpKey:{get:c,set:c},checkState:e,isAdBlocking:e,getSafeUri:a(function(a){return a}),pageChange:a(b),setupSmartBeacons:a(b)});Object.defineProperty(window,"_sp_",a(f));EventTarget.prototype.addEventListener=function(a){"sp.blocking"!=a&&"sp.not_blocking"!=a&&g.apply(this,arguments)}})(Object.defineProperties);
```

![image](https://user-images.githubusercontent.com/29142494/34443321-9d32b546-ecc7-11e7-90e3-7888d8ddff16.png)

**Comment by ameshkov** [comment]
business-service.me#@##banner_ad

**Comment by AdamWr** [comment]
More examples:
`q.gs#@##bottom`
`j.gs#@##bottom`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/34444545-2607ae1a-eccf-11e7-8ecd-40cd59435410.png)

</details>
<br>

`dayt.se#$##synpit { height:1px!important; }`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/34444452-993b269c-ecce-11e7-85e7-fa89a65c097e.png)

</details>

<br>

`doulci.net#@##top_ad_game`
`tamilmovierockers.net###j401`
`tamilmovierockers.net#$##j401 ~ * { display: block!important; }`
`oploverz.net###btm_banner`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/34444477-bd474d68-ecce-11e7-8023-16338cc9031e.png)

</details>

**Comment by BlazDT** [comment]
Also the part "-optiker.de" of:
@@||werbung.qs-optiker.de^$domain=werbung.qs-optiker.de

**Comment by ameshkov** [comment]
Pushed an update, version 0.0.3.

To update right away:
Uninstall
Reload
Install again
Reload

**Comment by BlazDT** [comment]
Showing orange now:
```
Also the part "-optiker.de" of:
@@||werbung.qs-optiker.de^$domain=werbung.qs-optiker.de

Or "1.de" of:
@@||doubleclick.net^$domain=video.sport1.de
```

Still red:
```
Or ",>.ads300-thumb']" of:
teilzeithelden.de##.widget.box-content-sidebar[-ext-has='>.four-ads-blocks,>.ads300-thumb']

Or ",>.inner>h3:not(:has(>))']" of
berlin.de##.teaser[-ext-has='>.inner>h3>a.trakkking,>.inner>h3:not(:has(>))']
```

**Comment by AdamWr** [comment]
`tamilmovierockers.net#$##j401 ~ * { display: block!important; }`
`||gambar123.com/xf/trump/xyz_$domain=46.166.167.16`
`46.166.167.16##div[class^="semprotnenenmontok_"]`
`dobreprogramy.pl##body > :matches-css(background-image: /^url\(data:image\/(gif|jpg|jpeg|png);base64,/):matches-css(position:fixed)`
`facet.wp.pl##table[data-reactid] div[class^="_"][-ext-matches-css="background-image: *https://facet.wp.pl/*"][-ext-matches-css="background-color: rgb(242, 242, 242)"]`

**Comment by ameshkov** [comment]
Version 0.0.4 published

**Comment by Alex-302** [comment]
Another valid modifiers, marked as invalid - `xmlhttprequest`, `object-subrequest`
![image](https://user-images.githubusercontent.com/8361299/39629682-adce5332-4fb5-11e8-8a92-d5752992ab72.png)
![image](https://user-images.githubusercontent.com/8361299/39629714-c9108d04-4fb5-11e8-8a1f-39098d5b5c0e.png)

**Comment by ameshkov** [comment]
Plz file a new issue

**Comment by Alex-302** [comment]
Done.
