### ISSUE TITLE
Internationalized Domain Names

### ISSUE THREAD

**Issue by Anonymous142** [ameshkov/VscodeAdblockSyntax#10]
http://www.청와대.한국
http://한글코딩.org
http://내도메인.한국

in these domains are not invalid.
for ex) `한글코딩.org##div`

of course we can use like this
`xn--bj0bv9kgwxoqf.org##div`

i'm not sure.. but it seems not bad to have a think about it.

**Comment by ameshkov** [comment]
As I recall, not every ad blocker support Unicode domain names, and this extension is supposed to help you create filters whichever ad blocker you use.

Generally, I'd suggest to use Punycode and add a comment with the Unicode domain name. Something like this:
```
! 한글코딩.org
xn--bj0bv9kgwxoqf.org##div
```

**Comment by Anonymous142** [comment]
i got it. ublock origin supports, but other ad blockers could not support..
thank you.

**Comment by ameshkov** [comment]
Tbh, I thought it does not. if so, all the major ad blockers do support unicode domain names and we'd better reopen it.

**Comment by Crystal-RainSlide** [comment]
As I've seen [punycode.js](https://github.com/bestiejs/punycode.js) in Adblock, AdBlock Plus and ublock Origin's source, I think most adblockers support this already.
