### ISSUE TITLE
VSCode hangs on checking very long string

### ISSUE THREAD

**Issue by BlazDT** [ameshkov/VscodeAdblockSyntax#2]
`234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234af234234+234ß24234asdf35234234234asdfasdf23452352352aaf2asdfasdf34234+234ß24234af234234+234ß24234.ö#%#window.google = function();`

VS Code hangs upon checking this rule

**Comment by ameshkov** [comment]
Seems to be resolved now.
