### ISSUE TITLE
Redundant modifier sepatator is not detected

### ISSUE THREAD

**Issue by Alex-302** [ameshkov/VscodeAdblockSyntax#25]
![image](https://user-images.githubusercontent.com/8361299/55915165-a8474600-5bf1-11e9-86e3-62efda1e1428.png)
`/^https:\/\/.*?\/v2\/0\/[a-zA-Z0-9_-]{30,}$/$third-party,script,$domain=~techworld.com`

**Comment by chirag127** [comment]
Is this bug really pending from 2 years?

**Comment by ameshkov** [comment]
Currently, the plugin is capable of syntax highlighting.

Proper rules validation requires writing a language server which is a quite complicated task: https://github.com/ameshkov/VscodeAdblockSyntax/issues/24
