### ISSUE TITLE
Domains with "-" are marked as invalid

### ISSUE THREAD

**Issue by AdamWr** [ameshkov/VscodeAdblockSyntax#27]
For example rule like this `d-navi004.com###snsbox` is partially marked as invalid due to `-`.

![image](https://user-images.githubusercontent.com/29142494/57916443-1fc46100-7893-11e9-9a15-3704199f39bc.png)

**Comment by AdamWr** [comment]
Thank you for fast fix, but unfortunately it still happens with version 0.0.17

**Comment by yourduskquibbles** [comment]
Came here to make the same issue report - thank you for fixing so fast @ameshkov  :)
