### ISSUE TITLE
[FR] Add snippet

### ISSUE THREAD

**Issue by bestpika** [ameshkov/VscodeAdblockSyntax#40]
Is it possible to add a snippet function?
For example, entering `ag-removeparam` can generate a line `example.com$removeparam=`.
Although it looks like you've finished typing this, I was actually hoping to add a keyword prompt.
This way I can just type ag-re... and I can select the snippet I need.

Thank you.

**Comment by ameshkov** [comment]
As I recall, this type of things requires adding a "language server" so this duplicates #24.

I wish we could do this at some point, but generally, this is a very complicated task.
