### ISSUE TITLE
path modifier is colored as if incorrect syntax

### ISSUE THREAD

**Issue by Yuki2718** [ameshkov/VscodeAdblockSyntax#47]
I guess this SS is enough to explain the issue.

![vsc](https://user-images.githubusercontent.com/58900598/160242376-456a7971-8ed5-40f1-8bee-84ee633dfe4e.png)

**Comment by slavaleleka** [comment]
<img width="302" alt="slbdzdrv3jpd0" src="https://user-images.githubusercontent.com/45171506/170478943-4d504a1a-3aef-45e9-81c8-9d641ca673b4.png">
