### ISSUE TITLE
Support optional args in scriptlets

### ISSUE THREAD

**Issue by wavygecko** [ameshkov/VscodeAdblockSyntax#53]
Optional args in scriptlets don't seem to be supported currently, e.g.,

```adblock
vivo.sx##+js(aeld, , preventDefault)
```

(ref: https://github.com/gorhill/uBlock/wiki/Resources-Library#aeldjs-)

**Comment by scripthunter7** [comment]
known issue: https://github.com/ameshkov/VscodeAdblockSyntax/pull/50
