### ISSUE TITLE
[GitHub Linguist] `@media` rules?

### ISSUE THREAD

**Issue by krystian3w** [ameshkov/VscodeAdblockSyntax#56]
In AdGuard Filters maybe all usage was removed - maybe as outdated (or I can not remember files with ~13 rules).

I see these is now invalid at end:

```adb
rootblog.pl#$#@media all and (min-width: 1200px) { a[href*="news.google.com/publications/"] { visibility: hidden !important; } }
rootblog.pl#$#@media (min-width: 1200px) { a[href*="news.google.com/publications/"] { visibility: hidden !important; } }
```

```adb
rootblog.pl#$#@media all and (min-width: 1200px) { a[href*="news.google.com/publications/"] b { content: "Chcesz być na bieżąco?..." !important; font-weight: bold; position: absolute; left: 19%; color: var(--cs-color-site-background); background: var(--cs-color-site-background); visibility: visible !important; } }
rootblog.pl#$#@media (min-width: 1200px) { a[href*="news.google.com/publications/"] b { content: "Chcesz być na bieżąco?..." !important; font-weight: bold; position: absolute; left: 19%; color: var(--cs-color-site-background); background: var(--cs-color-site-background); visibility: visible !important; } }
```

In uBo run only as:

```adb
rootblog.pl##a[href*="news.google.com/publications/"]:matches-media((min-width: 1200px)):style(visibility: hidden !important;)
rootblog.pl##a[href*="news.google.com/publications/"] b::after:matches-media((min-width: 1200px)):style(content: "Chcesz być na bieżąco?..." !important; font-weight: bold; position: absolute; left: 19%; color: var(--cs-color-site-background); background: var(--cs-color-site-background); visibility: visible !important;)
```

Filters is useful for articles on `rootblog.pl` to hide nasty Google news promotion. For now only covered wide PC.

(I don't see opened issue in FiltersCompiler about this parole by gorhill - still rejected will be "key frames" or "supports")

**Comment by krystian3w** [comment]
Maybe should fixed by #50 if cover GitHub.

**Comment by scripthunter7** [comment]
@krystian3w @Alex-302 Please try the temporary fix [here](https://novalightshow.netlify.app/?grammar-type=url&grammar=https%3A%2F%2Fraw.githubusercontent.com%2Fscripthunter7%2FVscodeAdblockSyntax%2Ffix-media-queries%2Fsyntaxes%2Fadblock.tmLanguage.json&sample-type=url&sample=https%3A%2F%2Fraw.githubusercontent.com%2Fscripthunter7%2FVscodeAdblockSyntax%2Ffix-media-queries%2Ftest_rules.txt)

Commit reference: https://github.com/scripthunter7/VscodeAdblockSyntax/commit/b815876ad1e0c1b5e45d0c37f6cb02401bb12674

**Comment by scripthunter7** [comment]
@krystian3w It seems that the new version has been uploaded to GitHub, but it will take some time before it will work properly everywhere:

```adblock
#$#@media (a: b) { .selector { a: b; } }
```
