### ISSUE TITLE
[GitHub Linguist] to=, from= and method= network filter options

### ISSUE THREAD

**Issue by MasterKia** [ameshkov/VscodeAdblockSyntax#58]
@scripthunter7  Hi, there are some new uBlock Origin syntax; I thought I'd let you know.

`from=` is an alias for `domain=` and `to=` is a superset of `denyallow=`:
https://github.com/gorhill/uBlock/commit/19f8b30d577ac17097b8060adfc92093866e26d8

`method=`:
https://github.com/gorhill/uBlock/commit/b6981877ba8f9011292aee9556c4d4c08c1bfd2d

Thanks.

**Comment by scripthunter7** [comment]
@MasterKia It seems that the new version has been uploaded to GitHub, but it will take some time before it will work properly everywhere:

```adblock
||google.com^$method=post|get
||example.com^$method=~get
```

**Comment by scripthunter7** [comment]
> Should I open another issue?

@MasterKia I think it's a good idea because it's a bit different topic and it's easier to manage that way. Thanks!

**Comment by scripthunter7** [comment]
@MasterKia This seems to be a bug, please open a separate issue for this
